# Configuration file
# key = value
quarkus.http.port=8083
quarkus.mongodb.projects.connection-string = mongodb://localhost:27017
quarkus.mongodb.application-name=Project-Services
projects-database-name=dontCodeDevProjects
data-database-name=dontCodeDevData
%test.projects-database-name=unitTestProjectDb
%test.data-database-name=unitTestDataDb


%scalewaytest.quarkus.http.port=8083
%scalewaytest.quarkus.http.host=127.0.0.1
%scalewaytest.quarkus.mongodb.projects.connection-string = mongodb://dontCodeTest:testPassword@localhost:27017/?authSource=admin
%scalewaytest.projects-database-name=dontCodeTestProjects
%scalewaytest.data-database-name=dontCodeTestData

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/

quarkus.package.jar.type=uber-jar
# Default memory type
quarkus.langchain4j.chat-memory.type=MESSAGE_WINDOW
# Maximum messages in memory (for MESSAGE_WINDOW)
quarkus.langchain4j.chat-memory.memory-window.max-messages=10

quarkus.langchain4j.mistralai.chat-model.model-name=codestral-latest

quarkus.log.level=INFO
quarkus.log.category."net.dontcode.prj".level=DEBUG
