name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create mongo Docker container
      id: build_mongo_docker
      uses: DigiPie/mongo-action@v1.0.1
      with:
        image-version: latest
        port: 27017
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '16'
    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: .m2/repository # maven repository files are stored here
        key: ${{ runner.OS }}-maven-${{ hashFiles('pom.xml') }}
    - name: Override Mongo connection url
      uses: myci-actions/export-env-var@1
      with:
        name: _TEST_QUARKUS_MONGODB_PROJECTS_CONNECTION_STRING
        value: "mongodb://localhost:27017"
    - name: Install
      run: |
         git config user.name "GitHub Actions"
         git config user.email noreply@github.com
         git merge origin/Development
    - name: override Mongo connection url
      uses: myci-actions/export-env-var@1
      with:
        name: _TEST_QUARKUS_MONGODB_PROJECTS_CONNECTION_STRING
        value: "mongodb://localhost:27017"
    - name: Build
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v2
        # Test run screenshots only on failure
      if: success()
      with:
        name: project-services-runner.jar
        path: target/project-services-runner.jar
    - name: Push
      run: |
        git commit -a -m "New version" --allow-empty
        git push
    - name: Deploy to test
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.TEST_HOST_NAME }}
        username: root
        key: ${{ secrets.TEST_KEY }}
        passphrase: ${{ secrets.TEST_PASSPHRASE }}
        source: "target/project-services-runner.jar"
        target: "/home/dont-code/services"
        strip_components: 1
    - name: Restart test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_HOST_NAME }}
        username: root
        key: ${{ secrets.TEST_KEY }}
        passphrase: ${{ secrets.TEST_PASSPHRASE }}
        script:
          sudo -u dont-code /home/dont-code/bin/restart-service.sh project-services
